# Cadenas de Markov - Actividad

## 1. Cadenas de Markov

Supongamos que el clima de la Magdalena Contreras sólo puede ser de dos maneras: soleado $s_1$ o nublado $s_2$ y que las condiciones del clima en mañanas sucesivas forman una cadena de Markov con probabilidades de transición estacionarias.

La matriz de transición está dada por:

$$
P = \begin{pmatrix}
0.4 & 0.6 \\
0.7 & 0.3
\end{pmatrix}
$$

Donde:
- Fila 1 y Columna 1: Soleado ($s_1$)
- Fila 2 y Columna 2: Nublado ($s_2$)


In [18]:
import numpy as np

# Definimos la matriz de transición P para el problema 1
# P[i,j] es la probabilidad de pasar del estado i al estado j
# s1: Soleado (indice 0), s2: Nublado (indice 1)
P1 = np.array([[0.4, 0.6],
               [0.7, 0.3]])

print("Matriz de transición P1:")
print(P1)


Matriz de transición P1:
[[0.4 0.6]
 [0.7 0.3]]


### Probabilidades de un paso

**a) Si un día en concreto está nublado. ¿Cuál es la probabilidad de que esté nublado el día siguiente?**

Estamos en el estado $s_2$ (nublado) y queremos la probabilidad de ir al estado $s_2$ (nublado) en el siguiente paso. Esto corresponde a $P_{22}$ (índice `[1,1]` en Python).


In [19]:
prob_a = P1[1, 1]
print(f"a) Probabilidad de nublado dado nublado: {prob_a} = {prob_a*100:.0f}%")


a) Probabilidad de nublado dado nublado: 0.3 = 30%


**b) Si un día en concreto está soleado. ¿Cuál es la probabilidad de que esté nublado el día siguiente?**

Estamos en el estado $s_1$ (soleado) y queremos la probabilidad de ir al estado $s_2$ (nublado) en el siguiente paso. Esto corresponde a $P_{12}$ (índice `[0,1]` en Python).


In [20]:
prob_b = P1[0, 1]
print(f"b) Probabilidad de nublado dado soleado: {prob_b} = {prob_b*100:.0f}%")


b) Probabilidad de nublado dado soleado: 0.6 = 60%


### Matriz de transición en dos pasos ($P^2$)

Calculamos $P^2 = P \times P$ para determinar las probabilidades después de dos días.


In [21]:
P1_2 = np.linalg.matrix_power(P1, 2)
print("Matriz de transición en dos pasos P^2:")
print(P1_2)


Matriz de transición en dos pasos P^2:
[[0.58 0.42]
 [0.49 0.51]]


**a) Si un día en concreto está soleado. ¿Cuál es la probabilidad de que dos días después esté soleado?**

Corresponde a $P^2_{11}$ (índice `[0,0]`).


In [22]:
prob_2a = P1_2[0, 0]
print(f"a) Probabilidad de soleado en 2 días dado soleado hoy: {prob_2a:.2f} = {prob_2a*100:.0f}%")


a) Probabilidad de soleado en 2 días dado soleado hoy: 0.58 = 58%


**b) Si un día en concreto está nublado. ¿Cuál es la probabilidad de que dos días después esté soleado?**

Corresponde a $P^2_{21}$ (índice `[1,0]`).


In [23]:
prob_2b = P1_2[1, 0]
print(f"b) Probabilidad de soleado en 2 días dado nublado hoy: {prob_2b:.2f} = {prob_2b*100:.0f}%")


b) Probabilidad de soleado en 2 días dado nublado hoy: 0.49 = 49%


---

## 2. Clima de la CDMX (3 estados)

Supongamos que el clima de la CDMX sólo puede ser de tres maneras: soleado $s_1$, nublado $s_2$ y lluvioso $s_3$. Las condiciones forman una cadena de Markov con probabilidades de transición estacionarias.

La matriz de transición está dada por:

$$
P = \begin{pmatrix}
0.3 & 0.4 & 0.3 \\
0.2 & 0.6 & 0.2 \\
0.1 & 0.5 & 0.4
\end{pmatrix}
$$

Donde:
- 0: Soleado ($s_1$)
- 1: Nublado ($s_2$)
- 2: Lluvioso ($s_3$)


In [24]:
# Definimos la matriz P para el problema 2
P2 = np.array([[0.3, 0.4, 0.3],
               [0.2, 0.6, 0.2],
               [0.1, 0.5, 0.4]])

print("Matriz de transición P2:")
print(P2)


Matriz de transición P2:
[[0.3 0.4 0.3]
 [0.2 0.6 0.2]
 [0.1 0.5 0.4]]


### Probabilidades de un paso

**a) Si un día en concreto está nublado. ¿Cuál es la probabilidad de que esté lluvioso el día siguiente?**

Estado $s_2 \to s_3$, es decir $P_{23}$ (índice `[1,2]`).


In [25]:
prob_2a = P2[1, 2]
print(f"a) P(lluvioso | nublado) = {prob_2a} = {prob_2a*100:.0f}%")


a) P(lluvioso | nublado) = 0.2 = 20%


**b) Si un día en concreto está lluvioso. ¿Cuál es la probabilidad de que esté lluvioso el día siguiente?**

Estado $s_3 \to s_3$, es decir $P_{33}$ (índice `[2,2]`).


In [26]:
prob_2b = P2[2, 2]
print(f"b) P(lluvioso | lluvioso) = {prob_2b} = {prob_2b*100:.0f}%")


b) P(lluvioso | lluvioso) = 0.4 = 40%


**c) Si un día en concreto está soleado. ¿Cuál es la probabilidad de que esté nublado el día siguiente?**

Estado $s_1 \to s_2$, es decir $P_{12}$ (índice `[0,1]`).


In [27]:
prob_2c = P2[0, 1]
print(f"c) P(nublado | soleado) = {prob_2c} = {prob_2c*100:.0f}%")


c) P(nublado | soleado) = 0.4 = 40%


**d) Si un día en concreto está soleado. ¿Cuál es la probabilidad de que esté lluvioso el día siguiente?**

Estado $s_1 \to s_3$, es decir $P_{13}$ (índice `[0,2]`).


In [28]:
prob_2d = P2[0, 2]
print(f"d) P(lluvioso | soleado) = {prob_2d} = {prob_2d*100:.0f}%")


d) P(lluvioso | soleado) = 0.3 = 30%


**e) Si un día en concreto está nublado. ¿Cuál es la probabilidad de que esté soleado el día siguiente?**

Estado $s_2 \to s_1$, es decir $P_{21}$ (índice `[1,0]`).


In [29]:
prob_2e = P2[1, 0]
print(f"e) P(soleado | nublado) = {prob_2e} = {prob_2e*100:.0f}%")


e) P(soleado | nublado) = 0.2 = 20%


### Matriz de transición en dos pasos ($P^2$)


In [30]:
P2_2 = np.linalg.matrix_power(P2, 2)
print("Matriz P^2 para el problema 2:")
print(P2_2)


Matriz P^2 para el problema 2:
[[0.2  0.51 0.29]
 [0.2  0.54 0.26]
 [0.17 0.54 0.29]]


**a) Si un día en concreto está soleado. ¿Cuál es la probabilidad de que dos días después esté soleado?**

Corresponde a $P^2_{11}$ (índice `[0,0]`).


In [31]:
prob_2a_2 = P2_2[0, 0]
print(f"a) P2(soleado | soleado) = {prob_2a_2:.3f} = {prob_2a_2*100:.1f}%")


a) P2(soleado | soleado) = 0.200 = 20.0%


**b) Si un día en concreto está nublado. ¿Cuál es la probabilidad de que dos días después esté soleado?**

Corresponde a $P^2_{21}$ (índice `[1,0]`).


In [32]:
prob_2b_2 = P2_2[1, 0]
print(f"b) P2(soleado | nublado) = {prob_2b_2:.3f} = {prob_2b_2*100:.1f}%")


b) P2(soleado | nublado) = 0.200 = 20.0%


**c) Si un día en concreto está lluvioso. ¿Cuál es la probabilidad de que dos días después esté soleado?**

Corresponde a $P^2_{31}$ (índice `[2,0]`).


In [33]:
prob_2c_2 = P2_2[2, 0]
print(f"c) P2(soleado | lluvioso) = {prob_2c_2:.3f} = {prob_2c_2*100:.1f}%")


c) P2(soleado | lluvioso) = 0.170 = 17.0%


**d) Si un día en concreto está nublado. ¿Cuál es la probabilidad de que dos días después esté lluvioso?**

Corresponde a $P^2_{23}$ (índice `[1,2]`).


In [34]:
prob_2d_2 = P2_2[1, 2]
print(f"d) P2(lluvioso | nublado) = {prob_2d_2:.3f} = {prob_2d_2*100:.1f}%")


d) P2(lluvioso | nublado) = 0.260 = 26.0%
